site_name: Mosqlimate
site_email: mosqlimate@gmail.com
site_support: 'https://wellcome.org/news/new-digital-tools-use-climate-data-better-predict-and-prepare-infectious-diseases-outbreaks'

docs_dir: pages
site_dir: build

theme:
  name: "material"
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    primary: "white"
    accent: "green"
  features:
    - tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch
  font:
    text: 'Golos Text'
    code: 'Ubuntu'
  icon:
  logo: 'assets/img/logo-medium.png'
  favicon: 'assets/img/favicon.ico'
  highlightjs: true
  hljs_languages:
    - python

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: pt
          name: Português
          build: true
          nav_translations:
            Home: Início
            Data Platform: Plataforma de dados
            OviCounter: Conta Ovos 
            OviCounter Image Dataset: Imagens do Conta Ovos
            Team: Equipe
            Contact: Contato
            Products: Produtos

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Mosqlimate-project/
      name: Mosqlimate Project

copyright: Copyright &copy; 2023 -  Mosqlimate

extra_css:
  - vendors/neoteroi-mkdocs.css
  - vendors/neoteroi-cards.css
  - css/custom.css

markdown_extensions:
  - neoteroi.cards
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: 'index.md'
  - Data Platform: 'http://api.mosqlimate.org'
  - OviCounter: 'https://contaovos.dengue.mat.br/pt-br/'
  - OviCounter Image Dataset: 'egg-dataset.md'
  - Team: 'team.md'
  - Contact: 'index.html#contact'
  - Products: 'products.md'