site_name: Mosqlimate
site_email: flavio.codeco.coelho@fgv.br
site_support: 'https://wellcome.org/news/new-digital-tools-use-climate-data-better-predict-and-prepare-infectious-diseases-outbreaks'

docs_dir: pages
site_dir: build

theme:
  name: "material"
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    primary: "white"
    accent: "green"
  features:
    - tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch
  font:
    text: 'Golos Text'
    code: 'Ubuntu'
  icon:
  logo: 'assets/img/logo-medium.png'
  favicon: 'assets/img/favicon.ico'
  highlightjs: true
  hljs_languages:
    - python

extra_css:
  - vendors/neoteroi-mkdocs.css
  - vendors/neoteroi-cards.css

markdown_extensions:
  - neoteroi.cards

nav:
  - Home: 'index.md'
  - Data Platform: 'http://api.mosqlimate.org'
  - Mosquito Surveillance: 'https://contaovos.dengue.mat.br/pt-br/'
  - Team: 'index.html#team'
  - Contact: 'index.html#contact'
