name: mosqlimate.io
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python
  - mkdocs
  - mkdocs-jupyter
  # dev
  - make
  - pre-commit
  - pyopengl
  - pip:
    - neoteroi-mkdocs
    - materialx
